import { addIcon } from '@iconify/react';
// @iconify-icons/ant-design
import AntDesignOutlined from '@iconify-icons/ant-design/ant-design-outlined';
import AppstoreOutlined from '@iconify-icons/ant-design/appstore-outlined';
import CloudServerOutlined from '@iconify-icons/ant-design/cloud-server-outlined';
import DatabaseOutlined from '@iconify-icons/ant-design/database-outlined';
import ExportOutlined from '@iconify-icons/ant-design/export-outlined';
import FileGifOutlined from '@iconify-icons/ant-design/file-gif-outlined';
import FulllScreenExitOutlined from '@iconify-icons/ant-design/fullscreen-exit-outlined';
import FullScreenOutlined from '@iconify-icons/ant-design/fullscreen-outlined';
import GithubOutlined from '@iconify-icons/ant-design/github-outlined';
import MenuFoldOutlined from '@iconify-icons/ant-design/menu-fold-outlined';
import MenuOutlined from '@iconify-icons/ant-design/menu-outlined';
import MenuUnfoldOutlined from '@iconify-icons/ant-design/menu-unfold-outlined';
import PieChartOutlined from '@iconify-icons/ant-design/pie-chart-outlined';
import ProfileOutlined from '@iconify-icons/ant-design/profile-outlined';
import ReloadOutlined from '@iconify-icons/ant-design/reload-outlined';
import TableOutlined from '@iconify-icons/ant-design/table-outlined';
// @iconify-icons/carbon
import ChartCombo from '@iconify-icons/carbon/chart-combo';
import ChartHistogram from '@iconify-icons/carbon/chart-histogram';
import Dashboard from '@iconify-icons/carbon/dashboard';
import DataError from '@iconify-icons/carbon/data-error';
import Error from '@iconify-icons/carbon/error';
import Infomation from '@iconify-icons/carbon/information';
import Link from '@iconify-icons/carbon/link';
import LogoReact from '@iconify-icons/carbon/logo-react';
import NewTab from '@iconify-icons/carbon/new-tab';
import Notification from '@iconify-icons/carbon/notification';
import Parameter from '@iconify-icons/carbon/parameter';
import ToolKit from '@iconify-icons/carbon/tool-kit';
import TreeView from '@iconify-icons/carbon/tree-view';
import UserOnline from '@iconify-icons/carbon/user-online';
import WorkSpace from '@iconify-icons/carbon/workspace';
// @iconify-icons/lucide
import ArrowLeftRight from '@iconify-icons/lucide/arrow-left-right';
import ArrowLeftToLine from '@iconify-icons/lucide/arrow-left-to-line';
import ArrowRightToLine from '@iconify-icons/lucide/arrow-right-to-line';
import ChevronDown from '@iconify-icons/lucide/chevron-down';
import ClipboardCopy from '@iconify-icons/lucide/clipboard-copy';
import Component from '@iconify-icons/lucide/component';
import Eye from '@iconify-icons/lucide/eye';
import EyeOff from '@iconify-icons/lucide/eye-off';
import FoldHorizontal from '@iconify-icons/lucide/fold-horizontal';
import FullScreen from '@iconify-icons/lucide/fullscreen';
import List from '@iconify-icons/lucide/list';
import ListTodo from '@iconify-icons/lucide/list-todo';
import LockKeyhole from '@iconify-icons/lucide/lock-keyhole';
import Mail from '@iconify-icons/lucide/mail';
import Pin from '@iconify-icons/lucide/pin';
import PinOff from '@iconify-icons/lucide/pin-off';
import Search from '@iconify-icons/lucide/search';
import ShieldCheck from '@iconify-icons/lucide/shield-check';
import SmartPhone from '@iconify-icons/lucide/smartphone';
import Upload from '@iconify-icons/lucide/upload';
import User from '@iconify-icons/lucide/user';
import X from '@iconify-icons/lucide/x';
// @iconify-icons/ri
import CommandLine from '@iconify-icons/ri/command-line';
import Css3Line from '@iconify-icons/ri/css3-line';
import Dashboard3Line from '@iconify-icons/ri/dashboard-3-line';
import FileCloudLine from '@iconify-icons/ri/file-close-line';
import FileDownloadLine from '@iconify-icons/ri/file-download-line';
import FileExcel2Line from '@iconify-icons/ri/file-excel-2-line';
import FileListLine from '@iconify-icons/ri/file-list-line';
import LogoutBoxRLine from '@iconify-icons/ri/logout-box-r-line';
import PagesLine from '@iconify-icons/ri/pages-line';
import Screenshot from '@iconify-icons/ri/screenshot-line';
// 本地图标，如菜单icon返回的是一个字符串，需要前端自行加载

// @iconify-icons/ant-design
addIcon('ant-design:github-outlined', GithubOutlined);
addIcon('ant-design:fullscreen-outlined', FullScreenOutlined);
addIcon('ant-design:fullscreen-exit-outlined', FulllScreenExitOutlined);
addIcon('ant-design:reload-outlined', ReloadOutlined);
addIcon('ant-design:pie-chart-outlined', PieChartOutlined);
addIcon('ant-design:appstore-outlined', AppstoreOutlined);
addIcon('ant-design:file-gif-outlined', FileGifOutlined);
addIcon('ant-design:profile-outlined', ProfileOutlined);
addIcon('ant-design:table-outlined', TableOutlined);
addIcon('ant-design:menu-outlined', MenuOutlined);
addIcon('ant-design:export-outlined', ExportOutlined);
addIcon('ant-design:ant-design-outlined', AntDesignOutlined);
addIcon('ant-design:database-outlined', DatabaseOutlined);
addIcon('ant-design:cloud-server-outlined', CloudServerOutlined);
addIcon('ant-design:menu-fold-outlined', MenuFoldOutlined);
addIcon('ant-design:menu-unfold-outlined', MenuUnfoldOutlined);
// @iconify-icons/carbon
addIcon('carbon:notification', Notification);
addIcon('carbon:information', Infomation);
addIcon('carbon:new-tab', NewTab);
addIcon('carbon:workspace', WorkSpace);
addIcon('carbon:dashboard', Dashboard);
addIcon('carbon:chart-histogram', ChartHistogram);
addIcon('carbon:data-error', DataError);
addIcon('carbon:error', Error);
addIcon('carbon:tree-view', TreeView);
addIcon('carbon:link', Link);
addIcon('carbon:logo-react', LogoReact);
addIcon('carbon:tool-kit', ToolKit);
addIcon('carbon:parameter', Parameter);
addIcon('carbon:user-online', UserOnline);
addIcon('carbon:chart-combo', ChartCombo);
// @iconify-icons/lucide
addIcon('lucide:user', User);
addIcon('lucide:eye', Eye);
addIcon('lucide:eye-off', EyeOff);
addIcon('lucide:lock-keyhole', LockKeyhole);
addIcon('lucide:smartphone', SmartPhone);
addIcon('lucide:mail', Mail);
addIcon('lucide:shield-check', ShieldCheck);
addIcon('lucide:search', Search);
addIcon('lucide:chevron-down', ChevronDown);
addIcon('lucide:fullscreen', FullScreen);
addIcon('lucide:x', X);
addIcon('lucide:pin', Pin);
addIcon('lucide:pin-off', PinOff);
addIcon('lucide:fold-horizontal', FoldHorizontal);
addIcon('lucide:arrow-left-right', ArrowLeftRight);
addIcon('lucide:arrow-left-to-line', ArrowLeftToLine);
addIcon('lucide:arrow-right-to-line', ArrowRightToLine);
addIcon('lucide:component', Component);
addIcon('lucide:list-todo', ListTodo);
addIcon('lucide:list', List);
addIcon('lucide:upload', Upload);
addIcon('lucide:clipboard-copy', ClipboardCopy);
// @iconify-icons/ri
addIcon('ri:logout-box-r-line', LogoutBoxRLine);
addIcon('ri:command-line', CommandLine);
addIcon('ri:dashboard-3-line', Dashboard3Line);
addIcon('ri:pages-line', PagesLine);
addIcon('ri:css3-line', Css3Line);
addIcon('ri:file-list-line', FileListLine);
addIcon('ri:file-excel-2-line', FileExcel2Line);
addIcon('ri:file-download-line', FileDownloadLine);
addIcon('ri:screenshot-line', Screenshot);
addIcon('ri:file-cloud-line', FileCloudLine);
