export const DB_CACHED_MENU_ITEMS_KEY = 'RA::DB_CACHED_MENU_ITEMS_KEY';
export const DB_CACHED_FLAT_MENU_ITEMS_KEY =
  'RA::DB_CACHED_FLAT_MENU_ITEMS_KEY';
export const DB_CACHED_TABS_KEY = 'RA::DB_CACHED_TABS_KEY';
